### ISSUE TITLE
大佬，能不能给下训练数据

### ISSUE THREAD

**Issue by youchunze** [CiyLei/InvoiceIdentify#1]

**Comment by CiyLei** [comment]
tessdata的训练数据吗，装个Tesseract-OCR自带的就好

**Comment by youchunze** [comment]
好的，谢谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CiyLei/InvoiceIdentify"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午2:58
收件人:&nbsp;"CiyLei/InvoiceIdentify"<InvoiceIdentify@noreply.github.com&gt;;
抄送:&nbsp;"阿怪"<958900021@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CiyLei/InvoiceIdentify] 大佬，能不能给下训练数据 (#1)





 
tessdata的训练数据吗，装个Tesseract-OCR自带的就好
